# Generated by Django 5.2.6 on 2025-09-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo', models.CharField(blank=True, max_length=50, null=True)),
                ('operador', models.CharField(blank=True, max_length=20, null=True)),
                ('ayudante', models.CharField(blank=True, max_length=20, null=True)),
                ('trabajo_realizar', models.TextField(max_length=100)),
                ('salida', models.TimeField()),
                ('llegada', models.TimeField()),
                ('termino', models.TimeField()),
                ('retorno', models.TimeField()),
                ('costo_hr_maniobra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('firma_cliente', models.ImageField(upload_to='firmas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nota_abierta', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
