# Generated by Django 5.2.6 on 2025-09-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_delete_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='costo_hr_maniobra',
            new_name='costo_hora',
        ),
        migrations.AddField(
            model_name='note',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='costo_total_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='total_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
