# Generated by Django 5.2.6 on 2025-09-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_costo_hr_maniobra_note_costo_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='equipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
