# Generated by Django 5.2.6 on 2025-09-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='firma_cliente',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='retorno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='termino',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='trabajo_realizar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
