# Generated by Django 5.2.6 on 2025-10-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_firma_cliente_alter_note_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='costo_hora',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='costo_total',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='costo_total_iva',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='firma_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='total_horas',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='trabajo_realizar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
